apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: astro 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: astro 
    spec:
      containers:
        - name: astro 
          image: astro1.azurecr.io/astro
          ports:
          - containerPort: 8080